site_name: alludocs Wiki
plugins:
  - search
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - search.suggest
    - content.code.copy
    - content.tooltips
markdown_extensions:
  - admonition
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - tables
nav:
  - Home: index.md
  - API Reference:
    - Item: reference/item.md
    - Block: reference/block.md
  - Items:
    - Basics: items/items.md
    - Tags: items/tags.md
    - Advanced: items/advanced.md
  - Blocks:
    - Basics: blocks/blocks.md
    - Materials: blocks/materials.md
    - Models: blocks/models.md